### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by naveedrocks1** [cdv-dev/Android-ATM-searcher#4]
Hi, i am getting this error

`Error:(10, 0) Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to "fdb008982536b6db5a58df11f2efac521ca05120"`
please help me fix this

**Comment by cdv-dev** [comment]
This error means that need to update version of gradle in the "build.gradle" file. I fixed it, see my last commit.

**Comment by naveedrocks1** [comment]
Can you please tell me why I can't seen any results? It just says Nothing
found. Does this work only in few areas?
